### ISSUE TITLE
High count error in raids.

### ISSUE THREAD

**Issue by Spunkette** [Aelexe/easy-bronze#1]
I got this while I was in MSV earlier.

Message: Interface/AddOns/EasyBronze/EasyBronze.lua:42: attempt to call field 'unregisterEvent' (a nil value)
Time: Sun Jun 16 19:20:09 2024
Count: 1062
Stack: Interface/AddOns/EasyBronze/EasyBronze.lua:42: attempt to call field 'unregisterEvent' (a nil value)
[string "@Interface/AddOns/EasyBronze/EasyBronze.lua"]:42: in function `callback'
[string "@Interface/AddOns/EasyBronze/modules/events.lua"]:8: in function <Interface/AddOns/EasyBronze/modules/events.lua:6>
[string "=[C]"]: ?
[string "@Interface/AddOns/LibSharedMedia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/LibSharedMedia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: (*temporary) = nil
(*temporary) = "UNIT_SPELLCAST_INTERRUPTED"
(*temporary) = "attempt to call field 'unregisterEvent' (a nil value)"

**Comment by Aelexe** [comment]
Thank you for the bug report. This should be fixed with v0.0.6.
