### ISSUE TITLE
Exclude gems doesn't work

### ISSUE THREAD

**Issue by Zazou89** [Aelexe/easy-bronze#3]
Hello,

I don't want to recycle my gems, whether I tick the gem boxes or not, they are still to be destroyed. I play with the game in French, is it linked to the client's language?

![image](https://github.com/Aelexe/easy-bronze/assets/155338110/4e49b35a-7588-47d0-b783-73ba8214a53a)
![image](https://github.com/Aelexe/easy-bronze/assets/155338110/cacf3064-9bdd-40ad-a7b3-5f281247313a)

**Comment by Zazou89** [comment]
Update : switched to English, now it's working, seems a client language related issue.

**Comment by Aelexe** [comment]
Thank you for the bug report. This is indeed an issue caused by my use of localised item type values, and will be fixed in the next release.
